version: "3.8"

services:
  mysqldb:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}"
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - medisync-network

  influxdb:
    image: influxdb:2.7
    ports:
      - "${INFLUXDB_PORT}"                   # Port mapping for InfluxDB
    volumes:
      - influxdb_data:/var/lib/influxdb2                # Persistent storage volume for InfluxDB data
    environment:
      - INFLUXDB_INIT_MODE=setup                        # Initial setup mode for InfluxDB 2.x
      - INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}     # Admin username
      - INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}     # Admin password
      - INFLUXDB_INIT_ORG=${INFLUXDB_ORG}               # Organization name
      - INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}         # Bucket name
      - INFLUXDB_INIT_RETENTION=0                       # Retention policy (0 = unlimited)
      - INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}     # Admin token for API access
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - medisync-network


  app:
    depends_on:
      mysqldb:
        condition: service_healthy
      influxdb:
        condition: service_healthy
    build: .
    ports:
      - "${APP_PORT}:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/${MYSQL_DATABASE}?useSSL=false",
        "spring.datasource.username": "${MYSQL_USER}",
        "spring.datasource.password": "${MYSQL_PASSWORD}",
        "spring.jpa.hibernate.ddl-auto": "update",
        "spring.influx.url": "http://influxdb:8086",
        "spring.influx.org": "${INFLUXDB_ORG}",
        "spring.influx.bucket": "${INFLUXDB_BUCKET}",
        "spring.influx.token": "${INFLUXDB_TOKEN}",
        "spring.influx.username": "${INFLUXDB_USERNAME}",
        "spring.influx.password": "${INFLUXDB_PASSWORD}"
      }'
    volumes:
      - .m2:/root/.m2
      - ./target:/app/target
    networks:
      - medisync-network

networks:
  medisync-network:

volumes:
  db:
  influxdb_data: